"! @testing ZCL_I_TRAVEL_TUM
"! @testing ZCL_C_TRAVEL_TUM
"! @testing ZCL_FLIGHT_LEGACY
"! @testing FUGR:ZFLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM ztc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.