*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ ZFLIGHT_BOOKSUPPL_C

    IMPORTING
       VALUE(VALUES) TYPE !ZTT_BOOKSUPPL_M.