*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTRAVEL_UPDATE_TASKU01.
                    "ZFLIGHT_BOOKSUPPL_C
INCLUDE LZTRAVEL_UPDATE_TASKU02.
                    "ZFLIGHT_BOOKSUPPL_D
INCLUDE LZTRAVEL_UPDATE_TASKU03.
                    "ZFLIGHT_BOOKSUPPL_U