*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ ZFLIGHT_TRAVEL_DELETE

    IMPORTING
       REFERENCE(IV_TRAVEL_ID) TYPE !ZTRAVEL_ID
    EXPORTING
       REFERENCE(ET_MESSAGES) TYPE !ZT_MESSAGE.