*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ ZFLIGHT_TRAVEL_CALC_PRICE

    IMPORTING
       REFERENCE(IT_FLIGHT) TYPE !ZT_FLIGHT OPTIONAL.