*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ ZFLIGHT_TRAVEL_SET_BOOKING

    IMPORTING
       REFERENCE(IV_TRAVEL_ID) TYPE !ZTRAVEL-TRAVEL_ID
    EXPORTING
       REFERENCE(ET_MESSAGES) TYPE !ZT_MESSAGE.